spring.application.name=process-service
spring.datasource.url=jdbc:postgresql://localhost:5431/secret_database
spring.datasource.password=secret
spring.datasource.name=myuser
spring.liquibase.url=jdbc:postgresql://localhost:5431/secret_database
spring.liquibase.change-log=db/changelog/db.changelog-master.xml